### ISSUE TITLE
Current state of the project?

### ISSUE THREAD

**Issue by nicolas-hili** [SteKoe/ocl.js#164]
Dear @SteKoe, 

I am really interested in your project and it works pretty well!
I was wondering about the current state of it. The latest version available from npm is 1.2.0 while it seems you were working on the 1.3.0 version which adds (among other things) support for `let` expressions. I was wondering if you have any plan to release the last version. On the other hand, I found this [Github repository](https://www.npmjs.com/package/@luoyuxia/ocl.js) which seems to be a fork of yours (releasing v1.3.0) but I am not sure how the two projects are related.

Thanks for your inputs.

**Comment by SteKoe** [comment]
Hi @nicolas-hili,

I have just pushed 1.3.0 for you to npmjs.com ;) 
The project you have linked is "just" a fork of mine and I did not know of it before.

Best,
@SteKoe

**Comment by nicolas-hili** [comment]
Hi, @SteKoe thanks for your answer and the release of 1.3.0 to NPM :)
Let me know if I can help. I spotted some bugs and I'd be happy to open PRs to help you with that.
Cheers,

Nicolas
