### ISSUE TITLE
the 1.0.0-beta.8 version not working as expected using typescript

### ISSUE THREAD

**Issue by billyjov** [SteKoe/ocl.js#17]
for a simple use case like described in the doc i get  a error `window is not define` from `ocl.min.js`

**given**

``` 
import OclEngine from '@stekoe/ocl.js';

class Person {
    name: string;
    age: number;
    children: Person[];
    isMarried: boolean;
    husband: Person;
    wife: Person;
}

// const oclEngine = new OclEngine();

or 
const oclEngine = OclEngine.create();

```
**expected**
new instance of ocl engine

**got** 
`ReferenceError: window is not defined` from `node_modules\@stekoe\ocl.js\dist\ocl.min.js:1:286`

**Comment by SteKoe** [comment]
Is it possible to share your project setup which allows mit to reproduce the problem? I have tried several ways to include the the lib and faced no problems so far. Perhaps you might want to take a look at my example repository SteKoe/ocl.js-webpack-examples.
