### ISSUE TITLE
Support for enumerations

### ISSUE THREAD

**Issue by JDziurlaj** [SteKoe/ocl.js#19]
I have some rules that look like this in my UML tool:

```ocl
self.Type = VoterIdType::other implies not self.OtherType.oclIsUndefined()
```

or in English: `OtherType` must be defined when Type = other

`other` is a literal from the enumeration `VoterIdType`. `ocl.js` doesn't currently support enumerations, so I've ended up translating the rules to look something like this:

```ocl
context VoterId 
inv ViOtherTypeMustBeDefined: self.Type <> "other" implies self.OtherType->oclIsUndefined()
```

I'm thinking that an API call could be added called something like `registerEnumeration(name: string, literals: string[])`. I'm unsure what the impact would be on the parser side.

**Comment by SteKoe** [comment]
I have used your case as test basis and here is how I have implemented enumerations. Hope it helps you and works as expected :)

```
// The actual enum
const VoterIdType = {
    someVoterIdType: 'someVoterIdType',
    other: 'other'
};

// Use the enum
const voterId = {
    Type: VoterIdType.other,
    OtherType: undefined
};

// Register enum to OclEngine
oclEngine.registerEnum('VoterIdType', VoterIdType);

// Defined OCL expression that refers to enum
oclEngine.addOclExpression(`
    context Object inv ViOtherTypeMustBeDefined:
        self.Type = VoterIdType::other implies not self.OtherType.oclIsUndefined()
`);

// Let it run
let evaluationResult = oclEngine.evaluate(voterId);
expect(evaluationResult.getResult()).to.be.false;
```

**Comment by JDziurlaj** [comment]
This does work as expected. Thanks! Not to throw in another wrinkle, but... #21
