### ISSUE TITLE
Add support escape syntax support

### ISSUE THREAD

**Issue by JDziurlaj** [SteKoe/ocl.js#21]
We have enumerations defined like this:

![image](https://user-images.githubusercontent.com/7104454/45234097-b66f6580-b2a2-11e8-85ec-0de5761164b9.png)

Note the dashes in `state-id`, `state-voter-registration-id`, etc. 

The UML tool I use (MagicDraw) wouldn't accept rules like this:

```ocl
context VoterRecordsRequest 
inv VoterRegistrationRequired: self.Type->exists(c | c = VoterRequestType::ballot-request) implies self.OtherType->size() = 1
```

but it would work if the OCL escape sequence was used:

```ocl
context VoterRecordsRequest
inv VoterRegistrationRequired: self.Type->exists(c | c = VoterRequestType::_'ballot-request') implies self.OtherType->size() = 1
```

I'm not sure if this is standard behavior, but [Eclipse ](http://download.eclipse.org/ocl/doc/6.4.0/ocl.pdf) says it is

> Escape syntax for illegal names: type, operation, attribute, etc. names that correspond to OCL reserved
>words can be escaped in the standard fashion using a leading underscore (‘_’). In addition, names that
>contain spaces or tabs can be escaped by enclosing them in double-quotes (‘"’; this is non-standard).
>e.g., self.ownedRule->forAll(c : Constraint | c._context = self)

**Comment by SteKoe** [comment]
Hi John,

I have just pushed a change to the parser that should respect the escaping convention using `_'name-with-dashes'` and `_"name-with-dashes"`. Please give it a try!

Regards,
Stephan

**Comment by JDziurlaj** [comment]
Works for me! Thx @SteKoe !
