### ISSUE TITLE
`evaluatedContexts` Array is always empty

### ISSUE THREAD

**Issue by narayanan79** [SteKoe/ocl.js#210]
Ref: Example provided in https://github.com/SteKoe/ocl.js/issues/13

Hi @SteKoe ,

I am new to OCL.

`evaluatedContexts` Array is always empty in my example.
![image](https://user-images.githubusercontent.com/2851389/122718481-9f9b3180-d28a-11eb-92e7-6411e34f51de.png)

Appreciate help in letting know what is wrong in the code?

https://codesandbox.io/s/rule-engine-ocl-js-z38c2?file=/src/App.js

**Comment by SteKoe** [comment]
Ho @narayanan79,

`obj.constructor.name` in typeDeterminer function is always `OCLObject`. You have to change it to use the following function:

```
oclEngine.setTypeDeterminer((obj: any) => {
    return obj.type;
});
  ```

**Comment by narayanan79** [comment]
> Ho @narayanan79,
> 
> `obj.constructor.name` in typeDeterminer function is always `OCLObject`. You have to change it to use the following function:
> 
> ```
> oclEngine.setTypeDeterminer((obj: any) => {
>     return obj.type;
> });
> ```

Thank you. Will check it out.
