### ISSUE TITLE
Add deprecation for old npm package 'ocl-js' and redirect to new

### ISSUE THREAD

**Issue by billyjov** [SteKoe/ocl.js#24]
I guess the [old npm package](https://www.npmjs.com/package/ocl-js) is deprecated and **@stekoe/ocl.js** should be use instead. It's may be helpfull for other users to redirect the old package to the new.

**Comment by SteKoe** [comment]
I have pushed new versions to https://www.npmjs.com/package/ocl-js and https://www.npmjs.com/package/ocl.js which provide a link and hint to the new package. Hope that is sufficient. I have also added a `npm deprecated` message the previously mentioned repositories.
