### ISSUE TITLE
How about adding the link to the example repository to readme?

### ISSUE THREAD

**Issue by billyjov** [SteKoe/ocl.js#25]
It may usefull to add the link to the [example](https://github.com/SteKoe/ocl.js-webpack-examples) repository in the readme.

**Comment by SteKoe** [comment]
I was about to remove / deprecate them because I have included examples into this repository in examples folder.

**Comment by billyjov** [comment]
Then add a description on how to use/start examples will be helpfull for other users. 
This is completely missing in the documentation page, so I would rather write this here in the repository.

**Comment by SteKoe** [comment]
I have added the examples to the documentation which will be part of release 1.3.0.
