### ISSUE TITLE
TypeScript compiler not seeing declarations

### ISSUE THREAD

**Issue by JDziurlaj** [SteKoe/ocl.js#26]
When I compile my TypeScript project using the npm module `@stekoe/ocl.js`, it cannot find the `index.d.ts` file. 

```
error TS7016: Could not find a declaration file for module '@stekoe/ocl.js'. '/mycodepath/node_modules/@stekoe/ocl.js/dist/ocl.min.js' implicitly has an 'any' type.
  Try `npm install @types/stekoe__ocl.js` if it exists or add a new declaration (.d.ts) file containing `declare module '@stekoe/ocl.js';`
```

However if I move the `index.d.ts` up a level (to `ocl.js/`) and change its body to 
```
export * from './dist/components/OclEngine';
```
it works.

**Comment by SteKoe** [comment]
I have just added a "typings" key to the package.json that points to the `index.d.ts` file.
