### ISSUE TITLE
Support for removing existing ocl expressions from the list (evaluatedContexts)

### ISSUE THREAD

**Issue by billyjov** [SteKoe/ocl.js#27]
**Curent behavior**

using `addOclExpression` always store new expression in a list until the oclEngine Restart. This is a Problem as soon as a User try to use it in a `single page application` i.e dont restart the engine after give a expression.

**Desired behavior** 
next to `OclEngine.addOclExpression()` it will be good to have a methods like `OclEngine.removeOclExpression()` and/or `OclEngine.clearAllOclExpressions()`, in order to achieve the expected behavior in e.g in a SPA.

**Comment by SteKoe** [comment]
Hi there! 
I have added `removeOclExpression(oclExpression: string)` and `clearAllOclExpressions()`. Please give it a try.

**Comment by billyjov** [comment]
Can you please publish the **v1.1.0** on npm?

**Comment by SteKoe** [comment]
I have published the version
