### ISSUE TITLE
Create new instance of OclEngine throw error

### ISSUE THREAD

**Issue by billyjov** [SteKoe/ocl.js#28]
since version **v1.1.0** creating a new instance of `OclEngine` throw an error in typescript project.

**Given**

```
import { OclEngine } from '@stekoe/ocl.js';

const oclEngine = OclEngine.create();
```

**Then**
it throw an error.

`Cannot read property 'create' of undefined`. 
Sure using `new OclEngine()` does not work anymore because the class has no constructor.

**Comment by SteKoe** [comment]
Hi!

Would you mind to share your `tsc` compilerOptions since I am not able to reproduce the issue.

TIA!

**Comment by billyjov** [comment]
i tried it in a angular cli (**v6.2.5**) based project with the default `tsconfig`

**Comment by SteKoe** [comment]
Okay! I will give it a try and check the errors. I will report back asap!

**Comment by billyjov** [comment]
here a [stackblitz demo](https://stackblitz.com/edit/ocl-js-demo)

**Comment by SteKoe** [comment]
I have not found a solution, yet, however, if you use `import * as OclEngine from '@stekoe/ocl.js'` it at least works for now... I am still on finding a proper solution.

**Comment by billyjov** [comment]
nevertheless, we would not be able to access the methods of OclEngine because the index not allow this.

**Comment by SteKoe** [comment]
This issue is the same as #29.
