### ISSUE TITLE
OclEngine is default export, but not marked as such

### ISSUE THREAD

**Issue by JDziurlaj** [SteKoe/ocl.js#29]
In using the `ocl.js` in another TypeScript project, I'm running into an issue with the npm package. It appears that the `OclEngine` is the `default` export of the module, but it is not defined as such.

This causes code like this to fail
```typescript
import OclEngine from "@stekoe/ocl.js";
export class OclEngineFactory {
    public static getOclEngine() {
        const oclEngine =  OclEngine.create();
```

With an error like 
```
{
	"resource": "{}"
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'create' does not exist on type 'typeof import(\"{my_path}/node_modules/@stekoe/ocl.js/index\")'.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 38,
	"endLineNumber": 4,
	"endColumn": 44
}
```

It will work if I cast `OclEngine` to `any`, but that defeats the purpose of TypeScript.

**Comment by SteKoe** [comment]
The most current development branch should fix that problem. I will release a version as soon as I think it works in a stable way without breaking too much.
