### ISSUE TITLE
Use ES5 constructs for non-transpiled code

### ISSUE THREAD

**Issue by JDziurlaj** [SteKoe/ocl.js#34]
I am using `Jint` to call `ocl.js` from .NET. However, `Jint` only supports ES5 (mostly), and it is running into issues with the following code:

https://github.com/SteKoe/ocl.js/blob/02f9bef4062b2576d9494bd9891d75cb20743b3a/generator/grammar.jison#L358-L359

The issue is the use of the default values in the argument list, and the string interpolation on the second line.

**Comment by SteKoe** [comment]
I have removed `let` and `const` in favor of `var`, removed default params and the template string :) - Please give it a try!
