### ISSUE TITLE
Unable to create an instance of OclEngine: OclEngine is undefined

### ISSUE THREAD

**Issue by ayouboudelaa** [SteKoe/ocl.js#41]
Hi,
This maybe related to #28 and #29 .
I still unable to import `OclEngine` properly and create an instance of it. Using Typescript, I always get OclEngine `undefined` :

```typescript
import { OclEngine } from '@stekoe/ocl.js'
```

Error:
`TypeError: Cannot read property 'create' of undefined`

I also tried all the following with no luck:
```typescript
import OclEngine from '@stekoe/ocl.js'
```

```typescript
import * as OclEngine from '@stekoe/ocl.js'
```
I only got this to work using `require` which I don't prefer.

My `tsconfig.json` :
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "es2017",
      "es7",
      "es6",
      "dom"
    ],
    "strict": true,
    "sourceMap": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictNullChecks": false,
    "declarationDir": "dist/types",
    "outDir": "dist/library",
    "typeRoots": [
      "node_modules/@types"
    ],
    "baseUrl": "./"
  },
  "include": [
    "src"
  ]
}
```

**Comment by SteKoe** [comment]
Does this issue apply to version 1.2.0 which is published at npm repository or to the latest Snapshot on Github, too? I have pushed a Typescript example containing your tsconfig.json which seems to work, at least for me.

**Comment by ayouboudelaa** [comment]
@SteKoe yes this applies to version 1.2.0 installed through `npm`. I checked your example and I got the following when I ran `tsc` in `src` folder:

```
index.ts(3,29): error TS2339: Property 'create' does not exist on type 'typeof import(".../ocl.js/examples/ts/node_modules/@stekoe /ocl.js/dist/index")'.
```

Even the IDE I'm using (VSCode) is highlighting the `create` method as a not existing method on `OclEngine`.

A thing to mention, I was using ts-node to run the code above.

**Comment by SteKoe** [comment]
Does it work, when you install the library using `npm install git+https://github.com/SteKoe/ocl.js.git`? Have you tried that?

**Comment by ayouboudelaa** [comment]
Yes I tried that it doesn't work too. I will debug the library code to determine the problem.

**Comment by SteKoe** [comment]
Any news from your side? :)
