### ISSUE TITLE
Runtime Error - Couldn't find preset "@babel/preset-env"

### ISSUE THREAD

**Issue by gbtec-ext-enzotobio** [SteKoe/ocl.js#676]
Hi!
We encountered the following runtime error when trying to update the library:
`Couldn't find preset "@babel/preset-env" relative to directory "...\\node_modules\\@stekoe\\ocl.js"`

It seems to be caused by the babel configuration defined in the package.json:
https://github.com/SteKoe/ocl.js/blob/e7ffcd477fe67e04cf97f732fadc44f74e14ee77/package.json#L69
  
Removing it seems to solve the issue. I suspect that it might have been overlooked during the removal of Babel dependencies

Could you kindly review and confirm if the Babel configuration in the package.json was unintentionally left behind after removing Babel dependencies?

Thanks in advance

**Comment by SteKoe** [comment]
Hey @gbtec-ext-enzotobio ,
I have removed the entry. I will publish a release soon. Sorry für my late reply.

**Comment by SteKoe** [comment]
I have removed it in release v1.4.3
